# some_problems_by_python3